name: {{project_name.snakeCase()}}
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # intl
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.8
  pinput: ^4.0.0
  sliver_tools: ^0.2.12

  # Logging
  stack_trace: ^1.11.1
  logging: ^1.2.0
  pretty_dio_logger:
    ^1.3.1

  # Navigation
  go_router: ^13.2.4
  
  # overlay
  fluttertoast: ^8.2.5

  # State Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # services
  dio: ^5.4.3+1
  path: ^1.9.0
  image_picker: ^1.1.1

  # Classes & Functions
  fast_immutable_collections: ^10.2.2
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  fpdart: ^1.1.0
  form_builder_validators: ^10.0.1

  # Assets
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  lottie: ^3.1.1

  {{#with_firebase}}
  # Firebase
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  {{/with_firebase}}

  {{#with_remote_config}}
  firebase_remote_config: ^4.3.18
  {{/with_remote_config}}

  {{#with_cloud_messaging}}
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1+1
  {{/with_cloud_messaging}}

dev_dependencies:
  # test
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

  # splash & icons
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # generator
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  dart_mappable_builder: ^4.2.3

  # Navigation
  go_router_builder: ^2.5.1

  # Logging
  logger: ^2.2.0

  # Lints
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.2

# For information on the generic Dart part of "pubspec.yaml""../{{project_name.snackCase()}}"this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/icons/
  #   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
